@ToDoApp.API_HostAddress = https://localhost:44301

GET {{ToDoApp.API_HostAddress}}/api/tasks/user-tasks/1C48F7A0-2DBC-42D8-B31C-E53B6B2244B5
Accept: application/json

###

POST {{ToDoApp.API_HostAddress}}/api/tasks/add
Content-Type: application/json
{
  "UserId": "1C48F7A0-2DBC-42D8-B31C-E53B6B2244B5",
  "Title": "go to gym",
  "Note": "buy protein bar",
  "DueDate": "2025-07-13T05:30:00",
  "Priority": 2
}
###

Delete {{ToDoApp.API_HostAddress}}/api/tasks/delete/5B59BA9D-000D-40C0-9984-D40C4044BB1B
Content-Type: application/json

###


PUT {{ToDoApp.API_HostAddress}}/api/tasks/update
Content-Type: application/json
{
  "Id":"5AD07067-D57F-4E54-AABA-9A7B70D3E107",
  "Title": "go to gym",
  "Note": "buy 3 protein bars",
  "DueDate": "2025-07-13T05:30:00",
  "Priority": 2,
  "IsDone": true
}

###