@ToDoApp.API_HostAddress = https://localhost:44301

GET {{ToDoApp.API_HostAddress}}/api/tasks/user-tasks
Accept: application/json

###

POST {{ToDoApp.API_HostAddress}}/api/tasks/add
Content-Type: application/json
{
  "Title": "go to gym",
  "Note": "buy protein bar",
  "DueDate": "2025-07-20T05:30:00",
  "Priority": 2
}
###

Delete {{ToDoApp.API_HostAddress}}/api/tasks/delete/f588c7c6-bf5c-4103-9334-f57424333d9b
Content-Type: application/json

###


PUT {{ToDoApp.API_HostAddress}}/api/tasks/update
Content-Type: application/json
{
  "Id":"91a92362-1c2e-4149-a84a-4d4d6a23c367",
  "Title": "prepare for christmas trip",
  "Note": "prepare your passport",
  "DueDate": "2025-12-10T14:00:00",
  "Priority": 0,
  "IsDone": true
}

###